# Site settings
title: cmolisee
tagline: A developer blog.
description: A developer blog for developer things.
url: "https://cmolisee.github.io"
baseurl: ""

github:
  username: cmolisee

social:
  name: Cody Molisee
  email: molisee.cody@gmail.com
  links:
    - https://github.com/cmolisee

theme_mode: dark # light|dark

avatar: "/assets/banana.png"

# Build settings
markdown: kramdown
theme: null # custom styles
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-postcss

postcss:
  cache: false

paginate: 10

# GitHub Codespaces
# Allow connections from Codespaces forwarded ports
host: 0.0.0.0
port: 4000

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - tools
  - README.md
  - .editorconfig
  - .gitattributes
  - .devcontainer
